### ISSUE TITLE
fix primitive 570

### ISSUE THREAD

**Issue by abstraktor** [abstraktor/SqueakJS#10]
primitive 570 is broken. why? :D
see https://github.com/bertfreudenberg/SqueakJS/pull/30#discussion-diff-24679036

**Comment by abstraktor** [comment]
it's actually how we found it: https://github.com/bertfreudenberg/SqueakJS/blob/master/vm.js#L3581

**Comment by abstraktor** [comment]
@bertfreudenberg so should we change something based on your comment? (https://github.com/bertfreudenberg/SqueakJS/pull/30#discussion-diff-24679036)

**Comment by codefrau** [comment]
I don't see a need to implement prim 570 for the time being.
