### ISSUE TITLE
rename simplePush to pushConstants and make it an array

### ISSUE THREAD

**Issue by abstraktor** [abstraktor/SqueakJS#5]
- rename to pushConstants
- make it an array and do pointer arithmetic for accessing it (like `byte & 7`)
- make `op` in `generateStartOfNumericOp` an array with arithmetics too

see https://github.com/bertfreudenberg/SqueakJS/pull/30#discussion_r24672032
and https://github.com/bertfreudenberg/SqueakJS/pull/30#discussion_r24672609

**Comment by Nilos** [comment]
I am going to do this tomorrow!

**Comment by Nilos** [comment]
Fixed in e4f952d
