### ISSUE TITLE
peepholes checking sth twice

### ISSUE THREAD

**Issue by abstraktor** [abstraktor/SqueakJS#6]
- what does bert mean with doublecheck?
- make push push numbericOp jump match here

look at the peephole code with `Squeak.Compiler.comments = true`

`this.vm.findMethod('Set>>findElementOrNil:').compiled)` should contain

```
// 4 <11 75 B3> push push numericop > (peephole optimized)
if (typeof temp[7] === 'number') {
    stack[++vm.sp] = temp[7] > 0 ? vm.trueObj : vm.falseObj;
} else {
    stack[++vm.sp] = temp[7];
    stack[++vm.sp] = 0;
    vm.pc = 7; vm.sendSpecial(3); if (context !== vm.activeContext || vm.breakOutOfInterpreter !== false) return bytecodes + 7}
}
```

see https://github.com/bertfreudenberg/SqueakJS/pull/30#issuecomment-74284462

**Comment by codefrau** [comment]
I meant that your code was checking the type of the same temp var twice:

```
if (typeof temp[7]  === 'number') {...}
...
stack[++vm.sp] = temp[7] ... var a = stack[vm.sp - 1] ... if (typeof a === 'number' ...
```

Here, `a` is the same as `temp[7]`.
